name: Keep Render App Alive

on:
  schedule:
    - cron: "*/14 5-18 * * *"  
  workflow_dispatch:        

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to Render app
        run: |
          curl -s https://diamondmlproject.onrender.com > /dev/null
